import { SetMetadata } from '@nestjs/common';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const AGENTPROFILE_REPOSITORY = 'AGENTPROFILE_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const JSONRX_REPOSITORY = 'JSONRX_REPOSITORY';
export const WALLET_REPOSITORY = 'WALLET_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const TOPFIVE_REPOSITORY = 'TOPFIVE_REPOSITORY';
export const LOG_REPOSITORY = 'LOG_REPOSITORY';
export const IS_PUBLIC_KEY = 'isPublic';
export const Public = () => SetMetadata(IS_PUBLIC_KEY, true);
export const SW_TBL_SECURITY_QUESTION = 'SW_TBL_SECURITY_QUESTION';
export const SW_TBL_SECURITY_QUESTION_TEMP = 'SW_TBL_SECURITY_QUESTION_TEMP';
export const SW_TBL_SECURITY_QUESTION_HISTORY = 'SW_TBL_SECURITY_QUESTION_HISTORY';
export const SW_TBL_SECURITY_QUESTION_ANSWER_SET = 'SW_TBL_SECURITY_QUESTION_ANSWER_SET'
export const SW_TBL_PROFILE_AGENTS = 'SW_TBL_PROFILE_AGENTS'
export const SW_TBL_PROFILE_CUST = 'SW_TBL_PROFILE_CUST'
export const SW_TBL_PROFILE_MERCHANT = 'SW_TBL_PROFILE_MERCHANT'
